# Generated by Django 5.0 on 2023-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_profile_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload your profile image",
                null=True,
                upload_to="imgs/",
            ),
        ),
    ]
