# Generated by Django 5.0 on 2023-12-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work', to='portfolio.profile'),
        ),
    ]
