# Generated by Django 5.0 on 2023-12-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profile_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='link',
            field=models.CharField(blank=True, help_text='Enter project link', max_length=500, null=True),
        ),
    ]
